creation_rules:
  - path_regex: secrets\.(yaml|yml|json|env|ini)$
    key_groups:
      - age:
          - age1yubikey1qtwxgmr3ay562c5wrgh7veepnemejrnmx08ueyde42k5wxkh8qf8qk9lmr7
          - age1ga363sl0st48mv6vjghrkatvfng20tsp3am9j57eh22nwm03r4rqwcsz7c
