{
  imports = [
    ./bat.nix
    ./fish.nix
    ./bash.nix
    ./bat.nix
    ./clang.nix
    ./dircolors.nix
    ./direnv.nix
    ./eza.nix
    ./fzf.nix
    ./ghostty.nix
    ./gh-dash.nix
    ./git.nix
    ./git-cliff.nix
    ./gpg.nix
    ./helix.nix
    ./jujutsu.nix
    ./password-store.nix
    ./python.nix
    ./starship.nix
    ./yazi.nix
    ./zoxide.nix
    ./bins
    ./gtkwave
    ./tmux
  ];
}
