{
  imports = [
    ./control-center.nix
    ./dock.nix
    ./finder.nix
    ./image-capture.nix
    ./karabiner-elements.nix
    ./keybindings.nix
    ./keyboard.nix
    ./localisation.nix
    ./mail.nix
    ./printing.nix
    ./privacy.nix
    ./safari.nix
    ./screencapture.nix
    ./touchpad.nix
    ./ui.nix
  ];
}
