{
  imports = [
    ./bat.nix
    ./carapace.nix
    ./bash.nix
    ./bat.nix
    ./dircolors.nix
    ./direnv.nix
    ./eza.nix
    ./fish.nix
    ./fzf.nix
    ./ghostty.nix
    ./gh.nix
    ./git.nix
    ./git-cliff.nix
    ./gpg.nix
    ./helix.nix
    ./jujutsu.nix
    ./nushell.nix
    ./password-store.nix
    ./starship.nix
    ./tmux.nix
    ./uv.nix
    ./yazi.nix
    ./zoxide.nix
    ./bins
    ./gtkwave
  ];
}
