name: Setup Nix with caching
description: Install Nix with optimal settings and caching for CI workflows

inputs:
  github-token:
    description: GitHub token for authentication
    required: false
    default: ${{ github.token }}
  nixpkgs-branch:
    description: Nixpkgs branch to use
    required: false
    default: nixpkgs-unstable
  extra-nix-config:
    description: Additional Nix configuration
    required: false
    default: |
      sandbox = true

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: ${{ inputs.extra-nix-config }}
        github_access_token: ${{ inputs.github-token }}
        nix_path: nixpkgs=channel:${{ inputs.nixpkgs-branch }}

    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v13
