name: Auto-merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: write
  checks: read
  statuses: read

jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check required status checks
        uses: actions/github-script@v6
        id: check-status
        with:
          script: |
            const pr = context.payload.pull_request;
            const checks = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha,
            });
            const allSuccess = checks.data.check_runs.every(check => check.conclusion === 'success');
            if (!allSuccess) {
              core.setFailed('Not all status checks have passed.');
            }

      - name: Approve Dependabot PR
        if: success()
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Dependabot PR
        if: success()
        run: gh pr merge --squash --auto --delete-branch "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
