name: Update Nix Flake

on:
  schedule:
    - cron: "0 0 * * 6" # Every Saturday at midnight UTC
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write # Needed to commit and push changes

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Update Nix flakes
        run: nix flake update

      - name: Check for changes
        id: git-check
        run: |
          echo "::set-output name=changed::$(git status --porcelain | grep flake.lock || echo '')"

      - name: Commit and push changes
        if: steps.git-check.outputs.changed != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update flake"
          branch: main
          file_pattern: flake.lock
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
